language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "asldev"
    token:
      secure: "6b2032642cbb1356ca512591dc0e391f6cfbad4f"
jdk:
  - oraclejdk17
script:
  - ./gradlew sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'