language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "asldev"
    token:
      secure: "$SONAR_TOKEN"
jdk:
  - oraclejdk17
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'